### ISSUE TITLE
export type UrlParsed

### ISSUE THREAD

**Issue by uifox** [vikejs/vike#1184]
### Description

I am passing `urlParsed` from the server side to the client side using the `passToClient` technique and I would like to add `urlParsed` with proper type definition to my app specific `PageContext`. To achieve this, I would need to import [type UrlParsed](https://github.com/vikejs/vike/blob/71057e0256a44e4ab4abaf374675c629690c0672/vike/shared/addUrlComputedProps.ts#L13) but I cannot since it is not exported. Could you please export this type? Thanks.

**Comment by brillout** [comment]
Will do in a moment.

**Comment by brillout** [comment]
Pre-released as `vike@0.4.143-commit-dc6fea`.

I've renamed the type to `Url` (because `pageContext.urlParsed` is going to be renamed `pageCotnext.url` in the next major release).

I don't know if I asked you before, but would your company be up for [sponsoring](https://github.com/sponsors/brillout)?

**Comment by uifox** [comment]
Hey @brillout,
Thanks for the super fast response. I'll talk with management about sponsoring. Well deserved IMO, since doxo really benefits from this library!

**Comment by brillout** [comment]
Thanks, I appreciate it! And I'm glad you're benefiting from Vike. Let me know how it goes 👀.
