### ISSUE TITLE
0.4.144 +client.ts does not run when clientRendering is on

### ISSUE THREAD

**Issue by dajinchu** [vikejs/vike#1209]
### Description

`+client.ts` seems to only run when client rendering is off. In earlier versions (last checked 0.4.138) client.ts would run when client rendering is on.

I can certainly work around this by just adding my own hook to onRenderClient, but wanted to check if this is an intentional change?

reproduction:
https://github.com/dajinchu/vite-plugin-ssr/pull/new/dc/client-clientrouting

**Comment by brillout** [comment]
`+client.js` is meant for HTML-only pages. But I agree it would be useful for other use cases as well.

Let me have a look if I can quickly implement this.

**Comment by brillout** [comment]
Actually, the more I think about it, the more I'm inclined to think it's better to not do that and, instead, to use hooks such as `onHydrationEnd()` (and potentially new hooks).

What's your use case for `+client.js`?

**Comment by dajinchu** [comment]
Some client side code like CMS, i18n, error tracking has to be initialized before rendering starts. I can create a hook in onRenderClient instead?

**Comment by brillout** [comment]
👍 Yes sounds good. That way you have precise control over when your init code runs.

> before rendering starts

Executing such code at the beginning of the `+onRenderClient.js` file should do the trick, so that it starts running right away. (Although there isn't any guarantee that it will all happen *before* the rendering starts. If you want that you can call/await the code at the beginning of your `onRenderClient()` hook instead.)

I guess you wouldn't even need a new custom hook then. (Although it could make sense if you have different init code depending on the page.)

Let me know if something doesn't work out for you. Closing in the meantime.
