### ISSUE TITLE
Vike Extensions: GraphQL

### ISSUE THREAD

**Issue by brillout** [vikejs/vike#1373]
Develop Vike Extensions to automatically integrate with GraphQL tools such as Apollo and Relay.

I expect such Vike Extension to resemble [vike-react-query](https://github.com/vikejs/vike-react/tree/main/packages/vike-react-query); checking how `vike-react-query` is implemented is a good start.

Prior art:
 - Vike + Relay: https://github.com/XiNiHa/vilay (note that [vite-plugin-ssr = Vike](https://vite-plugin-ssr.com/vike))
 - Vike + Apollo + Vue: https://github.com/vikejs/vike/tree/main/examples/graphql-apollo-vue
 - Vike + Apollo + React: https://github.com/vikejs/vike/tree/main/examples/graphql-apollo-react
 - Vike + urql: https://vike.dev/urql

CC @AlecAivazis (creator of [Houdini GraphQL](https://github.com/HoudiniGraphql/houdini)).

**Comment by redbar0n** [comment]
More notes on Relay prior art:

[Vilay](https://github.com/XiNiHa/vilay) (Vite + vite-plugin-ssr aka. vike + Relay) has been archived, due to facing some bundling issues (likely something about re-wrapping Vike's exports as a separate package).

[nextjs-relay-streaming-ssr](https://github.com/tobias-tengler/nextjs-relay-streaming-ssr) which uses Next.js 14 App Router (and even React 18 streaming SSR). It has a pretty solid explanation in the Readme on **how it works**.

**Comment by brillout** [comment]
Closing in favor of https://github.com/vikejs/vike/issues/1715.
