### ISSUE TITLE
Extend prefetch() API

### ISSUE THREAD

**Issue by Robby6Strings** [vikejs/vike#1506]
### Description

It would be really great if the prefetch() API could return the data from the fetched route. For example, I'd like to get some context / meta data from the hovered link in order to show some kind of a preview.

**Comment by brillout** [comment]
Although I agree that'd be nice, I ain't sure how much of a priority this should be for the Vike team.

There are a couple of things that can increase the priority:
 - Further elaborating your use case. (The more we can see how much added value it adds the higher we'll increase the priority.)
 - Does any React/Vue/Solid framework out there support your use case? If yes that also increases the priority.
 - [Sponsoring Vike](https://github.com/vikejs/vike/issues/1350)

I'll go ahead and close this ticket because right now this ticket isn't considered to be in the short- nor middle-term roadmap. We'll re-open once this ticket lands on Vike's roadmap.
