### ISSUE TITLE
`Layout` nesting simply wraps `Page` wherever it is in the tree.

### ISSUE THREAD

**Issue by traviscooper** [vikejs/vike#1583]
### Description

Currently, creating a `Layout` nested under another folder with a `Layout` file will _fully_ replace the layout further up the tree with the one closest to the rendered page.  Shouldn't the nested `Layout` component simply wrap the `Page` component, and be mounted & rendered while inheriting all the `Layout`'s further up the tree (as the `Page` component itself does?).   

TL:DR; Should the `Layout` component just simply wrap the `Page`?

**Comment by brillout** [comment]
What's your use case for wanting [cumulative](https://github.com/vikejs/vike/issues/1283) Layouts?

The reason I went for non-cumulative Layouts is because the use case I had in mind is having pages that have different layouts, for example the landing page typically has a difference layout than an admin panel.

Closing but let's continue the discussion. Let's see if there is a better design to be discovered, and if there is, we can then open a clear roadmap feature request.

(I've seen you started to personally sponsor Vike, thank you :green_heart:)

**Comment by traviscooper** [comment]
My thinking was to replicate what [NextJS does with Layouts & nesting](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#layouts).  I initially wasn't convinced with how they do it, but have since come around to the benefits of it. 

After developing a lot with NextJS `app` pages, I think in practice you'd branch these two concerns  (for example a landing page and admin panel) at the very top, and allow all sub-pages to inherit layouts as you nest further down/into the page. 

I appreciate the feedback and background! I want to enable NextJS `app` router support by using Vike, but before I implemented it in my projects, I wanted to see if I missed something with the existing implementation.

**Comment by brillout** [comment]
Yes, Next.js's support for nested layouts is quite neat. It's very much on the radar and I've a couple of neat ideas around this. (You can see some of it at https://github.com/vikejs/vike/issues/1459 but there is more to it I didn't write down yet.)

In the meantime I guess the workaround depicated at https://vike.dev/Layout#nested-layouts is an acceptable (albeit clunky) solution?
