### ISSUE TITLE
Env Leak (Vite, Vike, Vike-Solid, Bun)

### ISSUE THREAD

**Issue by Blankeos** [vikejs/vike#1641]
### Description

Not sure if I should make this issue in `vite`, `vike`, `vike-solid`, or `bun`.

In either case, as mentioned on Discord: https://discord.com/channels/1105779924658303058/1239651439111045281

![image](https://github.com/vikejs/vike/assets/38070918/1f48ae62-78e8-4d5d-926e-334d2d4ce720)

Made a minimal reproduction here: https://github.com/Blankeos/vike-hono-env-bug

**Comment by brillout** [comment]
It does show a warning in development though, right? I'm thinking Vike should throw an error also in dev instead of merely showing a warning.

**Comment by brillout** [comment]
Ah, I see why I made it to only be a warning back then:
> Only a warning for faster development DX (e.g. when user toggles `ssr: boolean` or `onBeforeRenderIsomorph: boolean`)

**Comment by brillout** [comment]
I'll go ahead and close this, but let me know if you don't see any warning in which case it would be a bug.

Thanks for opening this bug report!

**Comment by Blankeos** [comment]
Ah yeah, yup. There's a warning. Didn't catch that. Thanks! So long as it fails me to do this at some point (builds), that's good enough.

Thanks as well!

<img width="1416" alt="image" src="https://github.com/vikejs/vike/assets/38070918/648d3e4f-7316-4a82-8be3-0d1d8e957a54">

**Comment by Blankeos** [comment]
Just to add to this. I'm now realizing that `config.ts` for all my environment variables is kinda bad.

I just wanted a single interface to access and document and give defaults for my environment variables. But I guess I can't do that here.

A better thing I did is to create two separate config files:
- `config.private.ts`
- `config.public.ts`

```ts
// config.private.ts

/** Only place private configurations here. */
export const privateConfig = {
  /** Port of the app (in dev). */
  PORT: (import.meta.env.PORT || 3000) as number,
  /** Development or Production. */
  NODE_ENV: (import.meta.env.NODE_ENV ?? "development") as
    | "development"
    | "production",
  /** DB-specific settings. */
  database: {
    /** The url of the database. */
    URL: import.meta.env.DATABASE_URL!,
    /** Not needed in development. https://docs.turso.tech/local-development#sqlite */
    AUTH_TOKEN: import.meta.env.DATABASE_AUTH_TOKEN!,
  },
  /** S3Bucket-specific settings. */
  s3: {
    /** Application Key ID in B2 (accessKeyId in S3) */
    ACCESS_KEY_ID: import.meta.env.S3_ACCESS_KEY_ID!,
    /** Application Key in B2 (secretAccessKey in S3) */
    SECRET_ACCESS_KEY: import.meta.env.S3_SECRET_ACCESS_KEY!,
    /** Name of the bucket. */
    BUCKET_NAME: import.meta.env.S3_BUCKET_NAME! ?? "spend-snap",
    /** Region of the bucket. */
    REGION: import.meta.env.S3_REGION! ?? "us-east-1",
    /** URL of the bucket. */
    ENDPOINT: import.meta.env.S3_ENDPOINT! ?? "http://localhost:4566",
  },
};
```

```ts
// config.public.ts

/** Only place public configurations here. */
export const publicConfig = {
  BASE_ORIGIN:
    import.meta.env.PUBLIC_ENV__BASE_ORIGIN || "http://localhost:3000",
};
```

Hope this helps out anyone who needs ideas on structure!

**Comment by brillout** [comment]
Curious: why not only using `.env` files? See https://vike.dev/env.

**Comment by brillout** [comment]
Makes sense. Although I'd export each variable individually [so that Rollup can do its tree-shaking](https://rollupjs.org/repl/?version=4.17.2&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q25pbXBvcnQlMjAlN0IlMjBjdWJlJTJDJTIwYmxhJTIwJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMuanMnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhibGEuYSklM0IlNUNuJTVDbmNvbnNvbGUubG9nKGN1YmUoNSkpJTNCJTIwJTJGJTJGJTIwMTI1JTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBtYXRocy5qcyU1Q24lNUNuZXhwb3J0JTIwY29uc3QlMjBibGElMjAlM0QlMjAlN0IlNUNuJTIwJTIwYSUzQTElMkMlNUNuJTIwJTIwJTJGJTJGJTIwSXNuJ3QlMjB0cmVlLXNoYWtlZCU1Q24lMjAlMjBiJTNBMiU1Q24lN0QlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjBmdW5jdGlvbiUyMGlzbid0JTIwdXNlZCUyMGFueXdoZXJlJTJDJTIwc28lNUNuJTJGJTJGJTIwUm9sbHVwJTIwZXhjbHVkZXMlMjBpdCUyMGZyb20lMjB0aGUlMjBidW5kbGUuLi4lNUNuZXhwb3J0JTIwY29uc3QlMjBzcXVhcmUlMjAlM0QlMjB4JTIwJTNEJTNFJTIweCUyMColMjB4JTNCJTVDbiU1Q24lMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBnZXRzJTIwaW5jbHVkZWQlNUNuJTJGJTJGJTIwcmV3cml0ZSUyMHRoaXMlMjBhcyUyMCU2MHNxdWFyZSh4KSUyMColMjB4JTYwJTVDbiUyRiUyRiUyMGFuZCUyMHNlZSUyMHdoYXQlMjBoYXBwZW5zISU1Q25leHBvcnQlMjBjb25zdCUyMGN1YmUlMjAlM0QlMjB4JTIwJTNEJTNFJTIweCUyMColMjB4JTIwKiUyMHglM0IlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjAlNUMlMjJzaWRlJTIwZWZmZWN0JTVDJTIyJTIwY3JlYXRlcyUyMGElMjBnbG9iYWwlNUNuJTJGJTJGJTIwdmFyaWFibGUlMjBhbmQlMjB3aWxsJTIwbm90JTIwYmUlMjByZW1vdmVkLiU1Q253aW5kb3cuZWZmZWN0MSUyMCUzRCUyMCdjcmVhdGVkJyUzQiU1Q24lNUNuY29uc3QlMjBpbmNsdWRlRWZmZWN0JTIwJTNEJTIwZmFsc2UlM0IlNUNuaWYlMjAoaW5jbHVkZUVmZmVjdCklMjAlN0IlNUNuJTVDdCUyRiUyRiUyME9uJTIwdGhlJTIwb3RoZXIlMjBoYW5kJTJDJTIwdGhpcyUyMGlzJTIwbmV2ZXIlNUNuJTVDdCUyRiUyRiUyMGV4ZWN1dGVkJTIwYW5kJTIwdGh1cyUyMHJlbW92ZWQuJTVDbiU1Q3R3aW5kb3cuZWZmZWN0MSUyMCUzRCUyMCdub3QlMjBjcmVhdGVkJyUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBZmFsc2UlMkMlMjJuYW1lJTIyJTNBJTIybWF0aHMuanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE).

**Comment by Blankeos** [comment]
Ahh right2! That is true. Thanks for this!

**Comment by Blankeos** [comment]
Hi Rom! revisiting this because I seem to encounter it again. But this time though, when I build, there's no error that prevents me from building. Which is a bit alarming. Since this makes it easy to leak env vars by mistake.

<img width="966" height="781" alt="Image" src="https://github.com/user-attachments/assets/953b4d24-3f3c-4539-b86f-130c5740ab38" />

I'm guessing this is technically possible because when a page is SSR'd, it renders it on the server so the server-side envs are read and saved into the html that's sent to the client.

**Comment by brillout** [comment]
>  the server-side envs are read and saved into the html that's sent to the client.

I ain't sure how Vike could protect you from doing that 👀
